version: '3.3'
services:
  mallory:
    image: zoobab/mallory
    container_name: mallory
    ports:
      - '1316:1316'
      - '1315:1315'
    volumes:
      - '$PWD/mallory.json:/root/.config/mallory.json'
      - '~/.ssh/id_rsa:/tmp/id_rsa'
